import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl font-bold text-red-500 underline">
          Hello World!
        </h1>
        <button className="text-blue-500 shadow-sm">Test</button>
      </main>
    </>
  );
}
